name: redd_mobile
description: A high-security, Rust-powered mobile wallet for the Redd ecosystem.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  ffi: ^2.1.0
  http: ^1.1.0
  path_provider: ^2.1.1
  flutter_native_splash: ^2.3.1
  android_12: true
  fullscreen: true
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_native_splash:
  android_12: true
  fullscreen: true
  color: "#0F0F0F"
  image: assets/branding/redd_logo_full.png
  android_12:
    image: assets/branding/redd_icon.png
    color: "#0F0F0F"

flutter:
  uses-material-design: true
  assets:
    - assets/branding/
