name: redd_mobile
description: "ReddMobile: Socially Sustainable Web3 Wallet"
version: 0.14.9+9
publish_to: 'none'

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  confetti: ^0.8.0
  app_links: ^3.4.0
  equatable: ^2.0.5
  app_links: ^3.4.0
  equatable: ^2.0.5
  flutter_secure_storage: ^9.2.4
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.3
  http: ^1.2.0
  bip39: 1.0.6
  hex: 0.2.0
  share_plus: 7.2.1
  path_provider: 2.1.2
  url_launcher: 6.3.1
  screenshot: 2.3.0
  mobile_scanner: 3.5.6
  image_picker: 1.0.4
  local_auth: 2.1.6
  qr_flutter: 4.1.0

dev_dependencies:
  confetti: ^0.8.0
  app_links: ^3.4.0
  equatable: ^2.0.5
  app_links: ^3.4.0
  equatable: ^2.0.5
  flutter_secure_storage: ^9.2.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
